# Generated by Django 4.2.1 on 2023-07-05 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orgainfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organame', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('landline', models.IntegerField()),
                ('mobile', models.IntegerField()),
                ('altmobile', models.IntegerField()),
                ('message', models.CharField(max_length=50)),
            ],
        ),
    ]
